author: Benjamin James Harrison-Sims
database: false
main: com.xegaming.xTroll.xTroll
name: xTroll
startup: postworld
version: '2.0'
depend: [Vault]
commands:
    trip:
        description: Trippin.
        usage: /<command> [Player/All]
    banish:
        description: BANISHMENT.
        usage: /<command> [Player]
    fakeop:
        description: For the lulz.
        usage: /<command> [Player/All]
    space:
        description: GIMMEH SPACE.
        usage: /<command>
