author: Benjamin James Harrison-Sims
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.tehrainbowguy.xtoys.XaldinToys
name: XaldinToys
startup: postworld
version: '1.0'
depend: [Vault]
commands:
    xt:
        description: Description
        usage: /<command> [arguments]
